<?php
namespace bwoester\geolocation;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


class Coordinates extends TBase {
  static $_TSPEC;

  public $latitude = null;
  public $longitude = null;
  public $altitude = null;
  public $accuracy = null;
  public $altitudeAccuracy = null;
  public $heading = null;
  public $speed = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'latitude',
          'type' => TType::DOUBLE,
          ),
        2 => array(
          'var' => 'longitude',
          'type' => TType::DOUBLE,
          ),
        3 => array(
          'var' => 'altitude',
          'type' => TType::DOUBLE,
          ),
        4 => array(
          'var' => 'accuracy',
          'type' => TType::DOUBLE,
          ),
        5 => array(
          'var' => 'altitudeAccuracy',
          'type' => TType::DOUBLE,
          ),
        6 => array(
          'var' => 'heading',
          'type' => TType::DOUBLE,
          ),
        7 => array(
          'var' => 'speed',
          'type' => TType::DOUBLE,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Coordinates';
  }

  public function read($input)
  {
    return $this->_read('Coordinates', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Coordinates', self::$_TSPEC, $output);
  }
}

class Position extends TBase {
  static $_TSPEC;

  public $coords = null;
  public $timestamp = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'coords',
          'type' => TType::STRUCT,
          'class' => '\bwoester\geolocation\Coordinates',
          ),
        2 => array(
          'var' => 'timestamp',
          'type' => TType::I64,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Position';
  }

  public function read($input)
  {
    return $this->_read('Position', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Position', self::$_TSPEC, $output);
  }
}


